name 'nareshnewcb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures nareshnewcb'
long_description 'Installs/Configures nareshnewcb'
version '0.1.0'
