name             'customers-list'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures customers-list'
long_description 'Installs/Configures customers-list'
version          '0.1.0'

depends 'selinux','~>0.9'
depends 'firewall', '~>2.5'
depends 'httpd', '~> 0.4'
depends 'mysql', '~> 7.0'
depends 'mysql2_chef_gem', '~> 1.1'
depends 'database', '~> 6.0'
